//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStoreCrmProject.DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Breed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Breed()
        {
            this.Animals = new HashSet<Animal>();
        }
    
        public int BreedID { get; set; }
        public string BreedName { get; set; }
        public int SpeciesCode { get; set; }
        public ColorType Color { get; set; }
        public SizeType Size { get; set; }
        public FurType FurType { get; set; }

        [NotMapped] // make sure this property is never reflected in the database
        public string SpeciesTypeFromCode // read only created to show in list view of Breeds
        {
            get
            {
                SpeciesType speciesType = (SpeciesType)SpeciesCode;
                return $"{speciesType}";
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal> Animals { get; set; }
    }
}
