//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStoreCrmProject.DataLayer
{
    using System;
    
    public enum ColorType : int
    {
        White = 1,
        Black = 2,
        Brown = 3,
        Gold = 4,
        Yellow = 5,
        Red = 6,
        Cream = 7,
        Blue = 8,
        Grey = 9,
        BlackTan = 10,
        BrownTan = 11,
        BlueTan = 12,
        IrishSpotted = 13,
        Flashy = 14,
        Patched = 15,
        Tuxedo = 16,
        RedMerle = 17,
        BlueMerle = 18,
        Harlequin = 19,
        Spotted = 20,
        BrownTicked = 21,
        BlueSpeckled = 22,
        Brindle = 23,
        Saddle = 24,
        Variety = 25
    }
}
