//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStoreCrmProject.DataLayer
{
    using System;
    
    public enum PositionType : int
    {
        Manager = 1,
        Administrator = 2,
        Veterinarian = 3,
        Trainer = 4,
        VetAssistant = 5,
        CareTaker = 6,
        Behaviorist = 7,
        Breeder = 8,
        Groomer = 9
    }
}
