//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStoreCrmProject.DataLayer
{
    using System;
    
    public enum ProvinceType : int
    {
        Alberta = 1,
        BritishColumbia = 2,
        Manitoba = 3,
        NewBrunswick = 4,
        NewfoundlandAndLabrador = 5,
        NorthwestTerritories = 6,
        NovaScotia = 7,
        Nunavut = 8,
        Ontario = 9,
        PrinceEdwardIsland = 10,
        Quebec = 11,
        Saskatchewan = 12,
        Yukon = 13
    }
}
