//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStoreCrmProject.DataLayer
{
    using System;
    
    public enum ServiceType : int
    {
        Treatment = 1,
        Vaccination = 2,
        Training = 3,
        Worming = 4,
        Neuturing = 5,
        Microchipping = 6,
        Grooming = 7
    }
}
