//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStoreCrmProject.DataLayer
{
    using System;
    
    public enum SpeciesType : int
    {
        Dog = 1,
        Cat = 2,
        GuineaPig = 3,
        Fish = 4,
        Bird = 5,
        Hamster = 6,
        Mouse = 7,
        Rabbit = 8,
        Rat = 9,
        Hedgehog = 10,
        Ferret = 11
    }
}
